# Site settings
---
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willmendesneto.github.io" # the base hostname & protocol for your site

# Build settings
layout: page
author: Wilson Mendes
author_biography: Google Developer Expert (GDE) AngularJS e Google Developer Group (GDG) Salvador Organizer. Estudioso das artes místicas das novas tecnologias, apaixonado por tecnologia e ativo em muitas comunidades, com foco em tecnologias para desenvolvedores web (Javascript, CSS, HTML, Workflow, desempenho da Web, segurança, etc), participando de algumas organizações de eventos e contribuir com projetos de código aberto. Músico e desenhista nas horas vagas.
author_biography_us: Google Developer Expert (GDE) AngularJS and Google Developer Group (GDG) Salvador Organizer. Student of the mystic arts of new technologies, passionate and active in many communities, focusing on technologies for web developers (Javascript, CSS, HTML, Workflow, Web performance, security, etc), some participating organizations events and contribute to open source projects. Musician and designer in his spare time.
author_biography_image: https://pt.gravatar.com/userimage/20307137/677413a79461cdfd62c8a65143214850.png?size=150
title: Willmendesneto Blog
website_author: http://about.me/willmendesneto/
image: https://pt.gravatar.com/userimage/20307137/677413a79461cdfd62c8a65143214850.png?size=300
website_keywords: angularjs, javascript, nodejs, grunt, php, performance, web, development, databases, git, github, jquery, mobile, mongodb, tdd, bdd, tests, agile, workflow, yeoman, html5 api
permalink: /:year/:month/:day/:title
email: willmendesneto@gmail.com
github_username: willmendesneto
github_repo_url: https://github.com/willmendesneto/willmendesneto.github.io.git
twitter_username: willmendesneto
description: This is my blog, when i talk about technologies
paginate: 20
markdown: kramdown
highlighter: pygments
disqus_short_name: willmendesneto
disqus_show_comment_count: true
google_analytics_tracking_id: ''

safe: true
---

This is the base Jekyll theme. You can find out more info about customizing your Jekyll theme, as well as basic Jekyll usage documentation at [jekyllrb.com](http://jekyllrb.com/)

You can find the source code for the Jekyll new theme at: [github.com/jglovier/jekyll-new](https://github.com/jglovier/jekyll-new)

You can find the source code for Jekyll at [github.com/jekyll/jekyll](https://github.com/jekyll/jekyll)
